# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('descriptions', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'A lot of Subscribers',
                'verbose_name': 'MySubscriber',
            },
        ),
    ]
